language: python
sudo: false
python:
  - "pypy-5.4.1"
  - "pypy3.3-5.2-alpha1"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
matrix:
  allow_failures:
    - python: nightly
install:
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov
script:
  py.test -v --cov flata
after_success:
  coveralls
notifications:
  email:
    recipients:
      - harry.ho_long@yahoo.com
    on_success: never # default: change
    on_failure: always # default: always